# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Web_Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify_txt_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='WiFiCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=120)),
                ('SSID', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
