# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_Web_Application', '0002_auto_20170717_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify_txt_users',
            name='Email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notify_txt_users',
            name='Phone_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=255),
        ),
    ]
